controllers:
    resource: ../src/Controller/
    type: attribute


Index:
    path: /
    controller: App\Controller\IndexController::HomePage

Contato:
    path: /contato
    controller: App\Controller\ContatoController::ContatoPage

About:
    path: /about/{slug}
    controller: App\Controller\AboutController::AboutPage

Mensagem:
    path: /messages/{id}/like/{direction}
    controller: App\Controller\MensagensController::MessagesLike